## Implementaion of Logic Gates using Perceptron

Logic Gates to implement for 3 i/p variables.


1. OR
2. NOT
3. XOR
4. XNOR
5. NAND
6. NOR
7. AND


Perceptron model function

$$ z = \sum_{i=1}^m(w_i * x_i) +b $$

Sigmoid Function

$$ f(z) =  \frac{1}{1 + e^{-z}} $$

Part 1.
Write a tensorflow program to implement a perceptron using functions described above for AND , OR and NAND logic gates. 
Choose weights and bias values accordingly.

## AND gate 

In [1]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[0],[0],[0],[1]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for AND GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  0.876559
iteration=  1000 cost=  0.529647
iteration=  2000 cost=  0.393386
iteration=  3000 cost=  0.317832
iteration=  4000 cost=  0.269514
iteration=  5000 cost=  0.235263
iteration=  6000 cost=  0.209296
iteration=  7000 cost=  0.188717
iteration=  8000 cost=  0.171903
iteration=  9000 cost=  0.157857
iteration=  10000 cost=  0.145922
iteration=  11000 cost=  0.135643
iteration=  12000 cost=  0.126692
Validating output for AND GATE
[[ 0.00567448]
 [ 0.13340551]
 [ 0.13559233]
 [ 0.80884409]]


## OR gate 

In [3]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[0],[1],[1],[1]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for OR GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  1.47753
iteration=  1000 cost=  0.394091
iteration=  2000 cost=  0.29855
iteration=  3000 cost=  0.238516
iteration=  4000 cost=  0.197504
iteration=  5000 cost=  0.167914
iteration=  6000 cost=  0.145639
iteration=  7000 cost=  0.128309
iteration=  8000 cost=  0.114475
iteration=  9000 cost=  0.103196
iteration=  10000 cost=  0.0938411
iteration=  11000 cost=  0.0859673
iteration=  12000 cost=  0.0792568
Validating output for OR GATE
[[ 0.16627915]
 [ 0.9340021 ]
 [ 0.93621552]
 [ 0.99904078]]


## NAND gate 

In [13]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[1],[1],[1],[0]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for NAND GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  0.746466
iteration=  1000 cost=  0.467316
iteration=  2000 cost=  0.365958
iteration=  3000 cost=  0.303616
iteration=  4000 cost=  0.260828
iteration=  5000 cost=  0.229254
iteration=  6000 cost=  0.20478
iteration=  7000 cost=  0.18514
iteration=  8000 cost=  0.16897
iteration=  9000 cost=  0.155395
iteration=  10000 cost=  0.143819
iteration=  11000 cost=  0.133822
iteration=  12000 cost=  0.125098
Validating output for NAND GATE
[[ 0.99454641]
 [ 0.8668493 ]
 [ 0.8671338 ]
 [ 0.18896069]]


Part 2. 
1. Use tensorflow library functions (Logical/Linear Regression )to find optimal weights and bias for all above mentioned gates.
2. Discuss the values choosen for epoch and stopping convergence. Plot the graph for accuracy v/s epoch.

In [15]:

# creating the weight and bias.
# The defined variables will be initialized to zero.
W = tf.Variable(0.0, name="weights")
b = tf.Variable(0.0, name="bias")


#  Creating placeholders for input X and label Y.
def inputs():
    """
    Defining the place_holders.
    :return:
            Returning the data and label lace holders.
    """
    X = tf.placeholder(tf.float32, name="X")
    Y = tf.placeholder(tf.float32, name="Y")
    return X,Y

# Create the prediction.
def inference(X):
    """
    Forward passing the X.
    :param X: Input.
    :return: X*W + b.
    """
    return X * W + b

def loss(X, Y):
    '''
    compute the loss by comparing the predicted value to the actual label.
    :param X: The input.
    :param Y: The label.
    :return: The loss over the samples.
    '''

    # Making the prediction.
    Y_predicted = inference(X)
    return tf.squared_difference(Y, Y_predicted)


# The training function.
def train(loss):
    learning_rate = 0.0001
    return tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)


with tf.Session() as sess:

    # Initialize the variables[w and b].
    sess.run(tf.global_variables_initializer())

    # Get the input tensors
    X, Y = inputs()

    # Return the train loss and create the train_op.
    train_loss = loss(X, Y)
    train_op = train(train_loss)

    # Step 8: train the model
    for epoch_num in range(num_epochs): # run 100 epochs
        for x, y in data:
          train_op = train(train_loss)

          # Session runs train_op to minimize loss
          loss_value,_ = sess.run([train_loss,train_op], feed_dict={X: x, Y: y})

        # Displaying the loss per epoch.
        print('epoch %d, loss=%f' %(epoch_num+1, loss_value))

        # save the values of weight and bias
        wcoeff, bias = sess.run([W, b])

Input_values = data[:,0]
Labels = data[:,1]
Prediction_values = data[:,0] * wcoeff + bias
plt.plot(Input_values, Labels, 'ro', label='main')
plt.plot(Input_values, Prediction_values, label='Predicted')

# Saving the result.
plt.legend()
plt.savefig('plot.png')
plt.close()

NameError: name 'num_epochs' is not defined